// <auto-generated />
using fmanagerFull.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace fmanagerFull.Migrations
{
    [DbContext(typeof(TransactionContext))]
    [Migration("20180321230545_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("fmanagerFull.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Balance");

                    b.Property<int>("Currency");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("fmanagerFull.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AccountToAddId");

                    b.Property<int?>("AccountToSubstractId");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Description");

                    b.Property<int>("Sum");

                    b.HasKey("Id");

                    b.HasIndex("AccountToAddId");

                    b.HasIndex("AccountToSubstractId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("fmanagerFull.Models.Transaction", b =>
                {
                    b.HasOne("fmanagerFull.Models.Account", "AccountToAdd")
                        .WithMany()
                        .HasForeignKey("AccountToAddId");

                    b.HasOne("fmanagerFull.Models.Account", "AccountToSubstract")
                        .WithMany()
                        .HasForeignKey("AccountToSubstractId");
                });
#pragma warning restore 612, 618
        }
    }
}
